### NUMPY
--Python ki Library

--Same list ki tarah hota hai

--Fast Hota hai

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
# if i will not give it in list there will be an error because array function takes list as an argument and convert it into array
arr = np.array([1,2,3,4,5,6])
arr.size

6

In [8]:
arr.shape # it will give us the shape of the array in tuple form (cols,rows)
type(arr) # it will give us the type of the array
arr.dtype # it will give us the data type of the array
arr.ndim # it will give us the number of dimensions of the array
arr.nbytes # it will give us the total number of bytes consumed by the array
arr.itemsize # it will give us the number of bytes consumed by each element of the array

8

In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2.shape

(2, 3)

In [10]:
arr2.ndim

2

### NUMPY Arrange

In [12]:
a2 = np.arange(1,10) # it will give us an array of numbers from 1 to 9
a2.shape

(9,)

In [13]:
a2.size

9

In [23]:
from PIL import Image
img = Image.open("/home/shahzaib/Downloads/cat.webp")
np.array(img)


array([[[227, 167,  89],
        [227, 167,  89],
        [228, 168,  90],
        ...,
        [145, 132, 125],
        [145, 133, 123],
        [145, 133, 123]],

       [[222, 162,  84],
        [222, 162,  84],
        [223, 163,  86],
        ...,
        [149, 137, 130],
        [148, 136, 126],
        [147, 135, 125]],

       [[214, 154,  76],
        [214, 154,  76],
        [215, 155,  77],
        ...,
        [152, 140, 130],
        [147, 135, 125],
        [143, 131, 122]],

       ...,

       [[211, 212, 207],
        [205, 204, 198],
        [196, 193, 185],
        ...,
        [ 97, 100,  99],
        [ 82,  85,  84],
        [ 54,  57,  56]],

       [[210, 210, 206],
        [218, 217, 213],
        [212, 208, 202],
        ...,
        [ 78,  80,  79],
        [ 61,  64,  63],
        [ 38,  40,  40]],

       [[200, 201, 196],
        [214, 212, 208],
        [205, 201, 195],
        ...,
        [ 61,  64,  63],
        [ 43,  45,  44],
        [  8,  10,   9]]

In [ ]:
img = np.array(img)
img.ndim

3

In [29]:
np.arange(64).reshape(8, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
# ghar pr jake check krna sari cheeze because jo para hai aj samaj nahi aya
